# SVD 
It stands for Singular Value Decomposition, and it is a mathematical technique used in linear algebra.
Singular Value Decomposition breaks down a matrix into three other matrices, revealing the underlying structure and patterns within the original matrix.
It has applications in various fields, including signal processing, statistics, machine learning, and data analysis.

A=UΣV^T
where:
U is an orthogonal matrix containing the left singular vectors.
Σ is a diagonal matrix containing the singular values.
V^T is the transpose of an orthogonal matrix containing the right singular vectors.

In [2]:
import numpy as np

In [3]:
def svd(matrix):
  # Step 1: Calculate the covariance matrix
  covariance_matrix = np.dot(matrix.T, matrix)

  # Step 2: Find the eigenvalues and eigenvectors of the covariance matrix
  eigenvalues, eigenvectors = np.linalg.eig(covariance_matrix)

  # Step 3: Sort the eigenvalues and eigenvectors in descending order of eigenvalue magnitude
  sorted_indices = np.argsort(eigenvalues)[::-1]
  eigenvalues = eigenvalues[sorted_indices]
  eigenvectors = eigenvectors[:, sorted_indices]

  # Step 4: Calculate the singular values (sqrt of eigenvalues)
  singular_values = np.sqrt(eigenvalues)

  # Step 5: Create the diagonal matrix of singular values
  sigma = np.diag(singular_values)

  # Step 6: Construct the left singular matrix (normalized eigenvectors)
  u = np.dot(matrix, eigenvectors) / singular_values

  # Step 7: Calculate the conjugate transpose of the right singular matrix
  vh = eigenvectors.T

  return u, sigma, vh

In [4]:
# Example usage
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

u, sigma, vh = svd(matrix)

In [5]:
# Print the original data
print("Original data:")
print(matrix)

Original data:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
# Print the transformed data
transformed_data = np.dot(u, np.dot(sigma, vh))
print("Transformed data:")
print(transformed_data)

Transformed data:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
